language: java
jdk:
  - oraclejdk8
script:
  - mvn clean graphwalker:generate-sources jacoco:prepare-agent test jacoco:report org.pitest:pitest-maven:mutationCoverage checkstyle:checkstyle findbugs:findbugs javadoc:javadoc graphwalker:test
